# Generated by Django 4.1.6 on 2023-02-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=100, null=True, verbose_name='CPF/CNPJ')),
                ('nome_empresa', models.CharField(max_length=100, null=True, verbose_name='Nome da empresa')),
                ('nome_fantasia', models.CharField(max_length=100, null=True, verbose_name='Nome fantasia')),
            ],
        ),
    ]
