# Generated by Django 4.1.6 on 2023-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painel_administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=100, null=True, verbose_name='CPF/CNPJ')),
                ('nome_empresa', models.CharField(max_length=100, null=True, verbose_name='Nome da empresa')),
                ('nome_fantasia', models.CharField(max_length=100, null=True, verbose_name='Nome fantasia')),
                ('multa', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de multa (%)')),
                ('juros_mensal', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de juros mensal (%)')),
            ],
        ),
    ]
