# Generated by Django 4.1.6 on 2023-02-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Painel',
            new_name='Painel_administrativo',
        ),
    ]
