# Generated by Django 4.1.6 on 2023-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painel_administrativo',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='painel_administrativo',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='painel_administrativo',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='painel_administrativo',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='painel_administrativo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='painel_administrativo',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='painel_administrativo',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='painel_administrativo',
            name='site',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='painel_administrativo',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='painel_administrativo',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
