# Generated by Django 4.1.6 on 2023-03-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_painel_administrativo_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painel_administrativo',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Site'),
        ),
    ]
