# Generated by Django 4.1.6 on 2023-02-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_rename_painel_painel_administrativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='painel_administrativo',
            name='juros_mensal',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de juros mensal (%)'),
        ),
        migrations.AddField(
            model_name='painel_administrativo',
            name='multa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de multa (%)'),
        ),
    ]
