# Generated by Django 4.1.6 on 2023-03-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_alter_painel_administrativo_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painel_administrativo',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='painel_administrativo',
            name='juros_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de juros mensal (%)'),
        ),
        migrations.AlterField(
            model_name='painel_administrativo',
            name='multa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de multa (%)'),
        ),
        migrations.AlterField(
            model_name='painel_administrativo',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='painel_administrativo',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome fantasia'),
        ),
    ]
