# Generated by Django 4.1.5 on 2023-01-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Indef', 'Não quero informar')], default='Indef', max_length=10, verbose_name='Sexo'),
        ),
    ]
