# Generated by Django 4.1.5 on 2023-01-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clientes_qualificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.CharField(choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], default=1, max_length=20, verbose_name='Tipo Cliente'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='qualificacao',
            field=models.CharField(choices=[('L', 'Locatário'), ('P', 'Proprietário'), ('F', 'Fiador')], default='L', max_length=15, verbose_name='Qualificação'),
        ),
    ]
