# Generated by Django 4.1.5 on 2023-01-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_clientes_tipo_cliente_alter_clientes_qualificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='celular',
            field=models.CharField(blank=True, max_length=10, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado_civil',
            field=models.CharField(choices=[(1, 'Casado(a)'), (2, 'Divorciado(a)'), (3, 'Solteiro(a)'), (4, 'Viúvo(a)')], default='', max_length=50, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='mae_cliente',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome da mae'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nacionalidade_cliente',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nascimento_cliente',
            field=models.CharField(blank=True, max_length=10, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='naturalidade_cliente',
            field=models.CharField(blank=True, max_length=50, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pai_cliente',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome do pai'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefone_residencial',
            field=models.CharField(blank=True, max_length=9, verbose_name='Telefone Residencial'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail'),
        ),
    ]
