# Generated by Django 4.1.5 on 2023-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_clientes_bairro_clientes_celular_clientes_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Orgão Expedidor'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='', max_length=10, verbose_name='Sexo'),
        ),
    ]
