# Generated by Django 4.1.6 on 2023-02-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro_Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contrato')),
                ('vencimento', models.DateField(blank=True, max_length=10, null=True, verbose_name='Contrato')),
                ('parcela', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contrato')),
                ('valor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contrato')),
                ('multa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contrato')),
                ('juros', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contrato')),
                ('valor_total', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contrato')),
            ],
        ),
    ]
