# Generated by Django 4.1.6 on 2023-02-14 12:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0042_alter_aluguel_regra_do_repasse_and_more'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contrato')),
                ('vencimento', models.DateField(blank=True, max_length=10, null=True, verbose_name='Vencimento')),
                ('parcela', models.CharField(blank=True, max_length=10, null=True, verbose_name='Parcela')),
                ('valor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Valor')),
                ('multa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Multa')),
                ('juros', models.CharField(blank=True, max_length=10, null=True, verbose_name='Juros')),
                ('valor_total', models.CharField(blank=True, max_length=10, null=True, verbose_name='Valor Total')),
                ('locatario', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='contrato', chained_model_field='contrato', default=None, on_delete=django.db.models.deletion.PROTECT, to='contratos.aluguel')),
            ],
        ),
        migrations.DeleteModel(
            name='Financeiro_Aluguel',
        ),
    ]
