# Generated by Django 4.1.6 on 2023-02-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0042_alter_aluguel_regra_do_repasse_and_more'),
        ('financeiro', '0002_aluguel_delete_financeiro_aluguel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluguel',
            new_name='Fin_Aluguel',
        ),
        migrations.AlterModelOptions(
            name='fin_aluguel',
            options={'verbose_name': 'Aluguel', 'verbose_name_plural': 'Alugueis'},
        ),
    ]
