# Generated by Django 4.1.6 on 2023-02-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_rename_aluguel_fin_aluguel_alter_fin_aluguel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_aluguel',
            name='locatario',
        ),
    ]
