# Generated by Django 4.1.5 on 2023-01-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], help_text='O cliente é Pessoa Física ou Jurídica?', max_length=2, verbose_name='Tipo Cliente')),
                ('qualificacao', models.CharField(choices=[('LOCATARIO', 'Locatário'), ('PROPRIETARIO', 'Proprietário'), ('FIADOR', 'Fiador')], max_length=12, verbose_name='Qualificação')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
