# Generated by Django 4.1.6 on 2023-02-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientepj',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome fantasia'),
        ),
    ]
