# Generated by Django 4.1.6 on 2023-03-06 18:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_clientes_tags_clientes_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='telefone_1',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='email_1',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='email_2',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='telefone_2',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='telefone_3',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='teste'), blank=True, null=True, size=None),
        ),
    ]
