# Generated by Django 4.1.5 on 2023-01-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_imoveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='proprietario_cliente', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='tipo_imovel',
            field=models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('SALA COMERCIAL', 'Sala comercial')], max_length=20, verbose_name='Tipo de Imóvel'),
        ),
    ]
