# Generated by Django 4.1.5 on 2023-01-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_imoveis_proprietario_alter_imoveis_tipo_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cpf_conjuge',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nome_conjunge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='proprietario',
            field=models.ForeignKey(limit_choices_to={'qualificacao': 'PROPRIETARIO'}, on_delete=django.db.models.deletion.PROTECT, related_name='proprietario', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
    ]
