# Generated by Django 4.1.6 on 2023-02-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_clientepf_cpf_alter_clientepj_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle_Chaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.CharField(max_length=100, null=True, verbose_name='Data e hora de retirada')),
                ('data_devolucao', models.CharField(max_length=100, null=True, verbose_name='Data e hora de devolução')),
                ('observacao', models.TextField(null=True, verbose_name='Observação')),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='cadastros.clientes', verbose_name='Cliente')),
                ('imovel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Imovel +', to='cadastros.imoveis', verbose_name='imovel')),
            ],
        ),
    ]
