# Generated by Django 4.1.5 on 2023-01-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_clientes_cpf_clientes_cpf_conjuge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='celular',
            field=models.CharField(blank=True, max_length=11, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='celular_conjuge',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='complemento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='data_expedicao',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Nascimento'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='data_expedicao_conjuge',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Nascimento'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado_civil',
            field=models.IntegerField(blank=True, choices=[('1', 'Casado(a)'), ('2', 'Divorciado(a)'), ('3', 'Solteiro(a)'), ('4', 'União Estável'), ('5', 'Viúvo(a)')], null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='mae_cliente',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome da mãe'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nascimento',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Nascimento'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Orgão Expedidor'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='orgao_expedidor_conjuge',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Orgão Expedidor'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pai_cliente',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome do pai'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='profissao_conjuge',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='rg_conjuge',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='sexo_conjuge',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Telefone Residencial'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefone_conjuge',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone Residencial'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf_conjuge',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
    ]
