# Generated by Django 4.1.6 on 2023-02-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_controle_chaves'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Controle_Chaves',
            new_name='Controle_de_Chaves',
        ),
    ]
