# Generated by Django 4.1.6 on 2023-02-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_rename_controle_chaves_controle_de_chaves'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Controle_de_Chaves',
            new_name='Saida_de_Chaves',
        ),
    ]
