# Generated by Django 4.1.5 on 2023-01-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_clientes_bairro_clientes_celular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imoveis',
            old_name='cep_imovel',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='imoveis',
            old_name='tipo_imovel',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='imoveis',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='imoveis',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='imoveis',
            name='complemento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='imoveis',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='imoveis',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='imoveis',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
