# Generated by Django 4.1.6 on 2023-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_controle_de_chaves_saida_de_chaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='data_devolucao',
            field=models.DateTimeField(max_length=100, null=True, verbose_name='Data e hora de devolução'),
        ),
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='data_retirada',
            field=models.DateTimeField(max_length=100, null=True, verbose_name='Data e hora de retirada'),
        ),
    ]
