# Generated by Django 4.1.5 on 2023-01-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_cep_imovel_imoveis_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='prop',
            field=models.ManyToManyField(to='cadastros.clientes'),
        ),
    ]
