# Generated by Django 4.1.5 on 2023-01-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_imoveis_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imoveis',
            name='prop',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo Cliente'),
        ),
    ]
