# Generated by Django 4.1.6 on 2023-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_saida_de_chaves_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='data_devolucao',
            field=models.TimeField(null=True, verbose_name='Data e hora de devolução'),
        ),
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='data_retirada',
            field=models.DateField(null=True, verbose_name='Data e hora de retirada'),
        ),
    ]
