# Generated by Django 4.1.5 on 2023-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_qualificacao_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualificacao_cliente',
            options={'verbose_name': 'Qualificação', 'verbose_name_plural': 'Qualificação'},
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='qualificacao',
        ),
        migrations.AddField(
            model_name='clientes',
            name='qualificacao',
            field=models.ManyToManyField(to='cadastros.qualificacao_cliente'),
        ),
    ]
