# Generated by Django 4.1.6 on 2023-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_saida_de_chaves_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='data_devolucao',
            field=models.DateTimeField(null=True, verbose_name='Data e hora de devolução'),
        ),
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='data_retirada',
            field=models.DateTimeField(null=True, verbose_name='Data e hora de retirada'),
        ),
    ]
