# Generated by Django 4.1.5 on 2023-01-29 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_qualificacao_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='proprietario',
            field=models.ForeignKey(limit_choices_to={'qualificacao': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='proprietario', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
    ]
