# Generated by Django 4.1.5 on 2023-01-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_imoveis_proprietario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qualificacao_Cliente',
            new_name='Qualificacao',
        ),
    ]
