# Generated by Django 4.1.6 on 2023-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_alter_saida_de_chaves_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='data_devolucao',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='hora_retirada',
            field=models.TimeField(null=True, verbose_name='Hora'),
        ),
    ]
