# Generated by Django 4.1.5 on 2023-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_rename_qualificacao_cliente_qualificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='endereco',
            field=models.CharField(default='', max_length=200, verbose_name='Endereço'),
        ),
    ]
