# Generated by Django 4.1.5 on 2023-01-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alter_imoveis_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='data_expedicao',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Data de Expedição'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='data_expedicao_conjuge',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Data de Expedição'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado_civil',
            field=models.IntegerField(blank=True, choices=[('1', 'Casado(a)'), ('2', 'Divorciado(a)'), ('3', 'Solteiro(a)'), ('4', 'União Estável'), ('5', 'Viúvo(a)')], null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='cidade',
            field=models.CharField(default=None, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='complemento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='endereco',
            field=models.CharField(default=None, max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='numero',
            field=models.CharField(default=None, max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='uf',
            field=models.CharField(default=None, max_length=2, verbose_name='UF'),
        ),
    ]
