# Generated by Django 4.1.6 on 2023-02-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alter_saida_de_chaves_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='data_retirada',
            field=models.DateField(default=None, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='hora_devolucao',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='hora_retirada',
            field=models.TimeField(default=None, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='saida_de_chaves',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
