# Generated by Django 4.1.5 on 2023-01-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_alter_clientes_data_expedicao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='qualificacao',
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='proprietario',
            field=models.ForeignKey(limit_choices_to={'qualificacao': '3'}, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_proprietario', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='qualificacao',
            field=models.CharField(blank=True, choices=[('1', 'Fiador'), ('2', 'Locatário'), ('3', 'Proprietário')], max_length=20, null=True, verbose_name='Qualificação'),
        ),
    ]
