# Generated by Django 4.1.5 on 2023-01-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_remove_clientes_qualificacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qualificacao',
        ),
    ]
