# Generated by Django 4.1.6 on 2023-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_imoveis_taxa_admin_anual_imoveis_taxa_admin_mensal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saida_de_chaves',
            name='taxa_admin_anual',
        ),
        migrations.RemoveField(
            model_name='saida_de_chaves',
            name='taxa_admin_mensal',
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='taxa_admin_anual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tx Adm Anual (%)'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='taxa_admin_mensal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tx Adm Mensal (%)'),
        ),
    ]
