# Generated by Django 4.1.5 on 2023-02-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_delete_qualificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='mae_cliente',
            new_name='mae',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='pai_cliente',
            new_name='pai',
        ),
    ]
