# Generated by Django 4.1.5 on 2023-02-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_rename_mae_cliente_clientes_mae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email_conjuge',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
    ]
