# Generated by Django 4.1.6 on 2023-02-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_remove_saida_de_chaves_taxa_admin_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='dias_para_repasse',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Dias para repasse'),
        ),
        migrations.AddField(
            model_name='imoveis',
            name='regra_do_repasse',
            field=models.CharField(choices=[('DIAS CORRIDOS', 'Dias corridos após o vencimento do aluguel')], default=None, max_length=100, verbose_name='Regra do repasse'),
        ),
        migrations.AddField(
            model_name='imoveis',
            name='repasse_garantido',
            field=models.CharField(choices=[('Não possui', 'Não possui'), ('Todo contrato', 'Garantir por todo contrato')], default=None, max_length=100, verbose_name='Repasse Garantido'),
        ),
    ]
