# Generated by Django 4.1.5 on 2023-02-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_clientes_email_conjuge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado_civil',
            field=models.IntegerField(blank=True, choices=[(1, 'Casado(a)'), (2, 'Divorciado(a)'), (3, 'Solteiro(a)'), (4, 'União Estável'), (5, 'Viúvo(a)')], null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='qualificacao',
            field=models.CharField(blank=True, choices=[('Fiador', 'Fiador'), ('Locatário', 'Locatário'), ('Proprietário', 'Proprietário')], max_length=20, null=True, verbose_name='Qualificação'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone_conjuge',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone Comercial'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='proprietario',
            field=models.ForeignKey(limit_choices_to={'qualificacao': 'Proprietário'}, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_proprietario', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='tipo',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Sala comercial', 'Sala comercial')], max_length=20, verbose_name='Tipo de Imóvel'),
        ),
    ]
