# Generated by Django 4.1.6 on 2023-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_imoveis_dias_para_repasse_imoveis_regra_do_repasse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento'),
        ),
    ]
