# Generated by Django 4.1.5 on 2023-02-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_alter_clientes_complemento_alter_clientes_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(blank=True, max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celular_conjuge',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone_conjuge',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Comercial'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
