# Generated by Django 4.1.6 on 2023-02-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_alter_clientes_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_proprietario', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
    ]
