# Generated by Django 4.1.6 on 2023-02-18 12:46

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_alter_imoveis_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='CPF'),
        ),
    ]
