# Generated by Django 4.1.6 on 2023-02-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_alter_clientes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cnpj',
            field=models.CharField(default=2, max_length=100, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
    ]
