# Generated by Django 4.1.6 on 2023-02-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0054_alter_financeiro_do_contrato_vencimento'),
        ('cadastros', '0024_remove_clientes_cnpj'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Clientes_PF',
        ),
    ]
