# Generated by Django 4.1.6 on 2023-02-18 19:01

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_rename_clientes_clientes_pf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes_pf',
            options={'verbose_name': 'Cliente PF', 'verbose_name_plural': 'Clientes PF'},
        ),
        migrations.AlterField(
            model_name='clientes_pf',
            name='cpf_conjuge',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='CPF'),
        ),
        migrations.CreateModel(
            name='Clientes_PJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('razao_social', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('nome_fantasia', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_abertura', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cep_sede', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('endereco', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('email_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('telefone_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('telefone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('telefone_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('tipo_responsavel_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('tipo_responsavel_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('responsavel_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cliente_PJ_responsavel_1', to='cadastros.clientes_pf', verbose_name='Responsável 1')),
                ('responsavel_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cliente_PJ_responsavel_2', to='cadastros.clientes_pf', verbose_name='Responsável 2')),
            ],
            options={
                'verbose_name': 'Cliente PJ',
                'verbose_name_plural': 'Clientes PJ',
            },
        ),
    ]
