# Generated by Django 4.1.6 on 2023-02-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_alter_clientes_pf_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes_pj',
            name='cep_sede',
        ),
        migrations.AddField(
            model_name='clientes_pj',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='clientes_pj',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='clientes_pj',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='clientes_pj',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='clientes_pj',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='clientes_pj',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='data_abertura',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='email_contato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Email contato'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='razao_social',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='telefone_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='telefone_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='telefone_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 3'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='tipo_responsavel_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='tipo_responsavel_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
