# Generated by Django 4.1.6 on 2023-02-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_remove_clientes_pj_cep_sede_clientes_pj_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes_pf',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientes_pf',
            name='mae',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='clientes_pf',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='clientes_pf',
            name='pai',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome do pai'),
        ),
        migrations.AlterField(
            model_name='clientes_pf',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='clientes_pf',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True, verbose_name='Tipo Cliente'),
        ),
    ]
