# Generated by Django 4.1.6 on 2023-02-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome / Razão Social')),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Clientes',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
