# Generated by Django 4.1.6 on 2023-02-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_clientesssss_pf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='nome_razao_social',
        ),
        migrations.AddField(
            model_name='clientes',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome'),
        ),
    ]
