# Generated by Django 4.1.6 on 2023-02-19 10:08

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_remove_clientes_nome_razao_social_clientes_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesssss_pf',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='celular_conjuge',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='cpf_conjuge',
            field=cpf_field.models.CPFField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='data_expedicao',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Data de Expedição'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='data_expedicao_conjuge',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Data de Expedição'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='email_conjuge',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='estado_civil',
            field=models.IntegerField(blank=True, choices=[(1, 'Casado(a)'), (2, 'Divorciado(a)'), (3, 'Solteiro(a)'), (4, 'União Estável'), (5, 'Viúvo(a)')], null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='mae',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='nascimento',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Nascimento'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='nome_conjunge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Orgão Expedidor'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='orgao_expedidor_conjuge',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Orgão Expedidor'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='pai',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome do pai'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='profissao_conjuge',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='rg_conjuge',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='sexo_conjuge',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='telefone_conjuge',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Comercial'),
        ),
        migrations.AddField(
            model_name='clientesssss_pf',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='clientesssss_pf',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
