# Generated by Django 4.1.6 on 2023-02-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_clientesssss_pf_bairro_clientesssss_pf_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesssss_pf',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='clientesssss_pf',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='clientesssss_pf',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='clientesssss_pf',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='clientesssss_pf',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='clientesssss_pf',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='clientesssss_pf',
            name='uf',
        ),
        migrations.AddField(
            model_name='clientes',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
