# Generated by Django 4.1.6 on 2023-02-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0034_remove_clientesssss_pf_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientesssss_PJ',
            fields=[
                ('clientes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.clientes')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(blank=True, max_length=20, null=True, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome fantasia')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('data_abertura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Data de abertura')),
                ('email_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Email contato')),
                ('telefone_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1')),
                ('telefone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('telefone_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 3')),
                ('tipo_responsavel_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo')),
                ('tipo_responsavel_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo')),
                ('responsavel_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cliente_PJ_responsavel_1', to='cadastros.clientes', verbose_name='Responsável 1')),
                ('responsavel_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cliente_PJ_responsavel_2', to='cadastros.clientes', verbose_name='Responsável 2')),
            ],
            bases=('cadastros.clientes',),
        ),
    ]
