# Generated by Django 4.1.6 on 2023-02-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_clientesssss_pj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesssss_pj',
            name='razao_social',
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_proprietario', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
    ]
