# Generated by Django 4.1.6 on 2023-02-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0036_remove_clientesssss_pj_razao_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes_pj',
            name='responsavel_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastros.Clientes_PJ.responsavel_1+', to='cadastros.clientes', verbose_name='Responsável 1'),
        ),
        migrations.AlterField(
            model_name='clientes_pj',
            name='responsavel_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastros.Clientes_PJ.responsavel_2+', to='cadastros.clientes', verbose_name='Responsável 2'),
        ),
    ]
