# Generated by Django 4.1.6 on 2023-02-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0037_alter_clientes_pj_responsavel_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesssss_pj',
            name='responsavel_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cliente_PJ_responsavel_1', to='cadastros.clientes', verbose_name='Responsável 1'),
        ),
        migrations.AlterField(
            model_name='clientesssss_pj',
            name='responsavel_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cliente_PJ_responsavel_2', to='cadastros.clientes', verbose_name='Responsável 2'),
        ),
    ]
