# Generated by Django 4.1.6 on 2023-02-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0039_clientes_tipo_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='tipo_cliente',
        ),
    ]
