# Generated by Django 4.1.6 on 2023-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0040_remove_clientes_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome'),
        ),
    ]
