# Generated by Django 4.1.6 on 2023-02-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0041_clientes_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
