# Generated by Django 4.1.6 on 2023-02-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0042_alter_clientes_nome_alter_clientes_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesssss_pj',
            name='proprietario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes_proprietario +', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
    ]
