# Generated by Django 4.1.6 on 2023-02-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0043_clientesssss_pj_proprietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesssss_pj',
            name='proprietario',
        ),
        migrations.AlterField(
            model_name='clientesssss_pj',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail de contato'),
        ),
        migrations.AlterField(
            model_name='clientesssss_pj',
            name='tipo_responsavel_1',
            field=models.CharField(blank=True, choices=[('Sócio', 'Sócio'), ('Procurador', 'Procurador')], max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='clientesssss_pj',
            name='tipo_responsavel_2',
            field=models.CharField(blank=True, choices=[('Sócio', 'Sócio'), ('Procurador', 'Procurador')], max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
