# Generated by Django 4.1.6 on 2023-02-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_remove_clientesssss_pj_proprietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesssss_pj',
            name='data_abertura',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='clientesssss_pj',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição estadual'),
        ),
    ]
