# Generated by Django 4.1.6 on 2023-02-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0045_alter_clientesssss_pj_data_abertura_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes_PJ',
        ),
    ]
