# Generated by Django 4.1.6 on 2023-02-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0046_delete_clientes_pj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes_PF',
        ),
    ]
