# Generated by Django 4.1.6 on 2023-02-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0047_delete_clientes_pf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientesssss_PF',
            new_name='ClientePF',
        ),
    ]
