# Generated by Django 4.1.6 on 2023-02-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0048_rename_clientesssss_pf_clientepf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientesssss_PJ',
            new_name='ClientePJ',
        ),
    ]
