# Generated by Django 4.1.6 on 2023-02-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0049_rename_clientesssss_pj_clientepj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientepf',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='clientepf',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientepf',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='clientepj',
            name='email_contato',
        ),
        migrations.RemoveField(
            model_name='clientepj',
            name='telefone_1',
        ),
        migrations.RemoveField(
            model_name='clientepj',
            name='telefone_2',
        ),
        migrations.RemoveField(
            model_name='clientepj',
            name='telefone_3',
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail de contato'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefone_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefone_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefone_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
