# Generated by Django 4.1.6 on 2023-02-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0050_remove_clientepf_celular_remove_clientepf_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='email',
        ),
        migrations.AddField(
            model_name='clientes',
            name='email_1',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='email_2',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
    ]
