# Generated by Django 4.1.6 on 2023-02-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0051_remove_clientes_email_clientes_email_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepj',
            name='data_situacao',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Data da situação'),
        ),
        migrations.AddField(
            model_name='clientepj',
            name='natureza_juridica',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Natureza Jurídica'),
        ),
        migrations.AddField(
            model_name='clientepj',
            name='porte',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Porte'),
        ),
        migrations.AddField(
            model_name='clientepj',
            name='situacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email_1',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail (1)'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email_2',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail (2)'),
        ),
    ]
