# Generated by Django 4.1.6 on 2023-03-06 18:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantia', models.CharField(choices=[('Não possui', 'Não possui'), ('Caução', 'Caução'), ('Fiador', 'Fiador'), ('Seguro fiança', 'Seguro fiança'), ('Título de capitalização', 'Título de capitalização')], default='Não possui', max_length=50, verbose_name='Garantia')),
                ('finalidade', models.CharField(blank=True, choices=[('Comercial', 'Comercial'), ('Industrial', 'Industrial'), ('Residencial', 'Residencial'), ('Temporada', 'Temporada')], max_length=50, null=True, verbose_name='Finalidade')),
                ('data_inicial', models.DateField(blank=True, null=True, verbose_name='Data inicial')),
                ('prazo_contrato', models.IntegerField(blank=True, null=True, verbose_name='Período (em meses)')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('valor_contrato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor do aluguel')),
                ('observacao_garantia', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_inicial_garantia', models.DateField(blank=True, null=True, verbose_name='Data inicial')),
                ('data_final_garantia', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('valor_garantia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor')),
                ('banco_garantia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco')),
                ('apolice_garantia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice')),
                ('seguradora', models.CharField(blank=True, max_length=50, null=True, verbose_name='Seguradora')),
                ('repasse_garantido', models.CharField(blank=True, choices=[('Não possui', 'Não possui'), ('Todo contrato', 'Garantir por todo contrato')], default=None, max_length=100, null=True, verbose_name='Repasse Garantido')),
                ('regra_do_repasse', models.CharField(blank=True, choices=[('DIAS UTEIS', 'Dias úteis após o vencimento do aluguel'), ('DIAS CORRIDOS', 'Dias corridos após o vencimento do aluguel')], default=None, max_length=100, null=True, verbose_name='Regra do repasse')),
                ('dias_para_repasse', models.IntegerField(blank=True, default=5, null=True, verbose_name='Dias para repasse')),
                ('taxa_admin_mensal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tx adm mensal (%)')),
                ('taxa_admin_anual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tx adm anual (%)')),
                ('fiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.clientes', verbose_name='Fiador')),
                ('imovel', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='proprietario', chained_model_field='proprietario', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.imoveis')),
                ('locatario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locatario +', to='cadastros.clientes', verbose_name='Locatário')),
                ('proprietario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes_proprietario +', to='cadastros.clientes', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Contrato de Aluguel',
                'verbose_name_plural': 'Contrato de Aluguel',
            },
        ),
        migrations.CreateModel(
            name='Financeiro_do_Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True, verbose_name='Parcela')),
                ('vencimento', models.DateField(blank=True, max_length=10, null=True, verbose_name='Vencimento')),
                ('vencimento_real', models.DateField(blank=True, max_length=20, null=True, verbose_name='Vencimento real')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data pagamento')),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor do Aluguel')),
                ('multa', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Multa')),
                ('juros', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Juros')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor total')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor pago')),
                ('saldo_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Saldo')),
                ('vencimento_repasse', models.DateField(blank=True, max_length=10, null=True, verbose_name='Vcto do repasse')),
                ('data_repasse', models.DateField(blank=True, max_length=10, null=True, verbose_name='Data do repasse')),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Comissão')),
                ('valor_repasse', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor do Repasse')),
                ('valor_repassado', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor repassado')),
                ('saldo_repasse', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Saldo a repassar')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato +', to='contratos.aluguel', verbose_name='Locatário e Imóvel')),
            ],
            options={
                'verbose_name': 'Financeiro',
                'verbose_name_plural': 'Financeiro do Contrato',
            },
        ),
        migrations.CreateModel(
            name='Administracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aluguel', models.CharField(default=None, max_length=20, verbose_name='Valor do aluguel')),
                ('taxa_admin_mensal', models.CharField(default=10, max_length=20, verbose_name='Tx Adm Mensal')),
                ('taxa_admin_anual', models.CharField(default=50, max_length=20, verbose_name='Tx Adm Anual')),
                ('data_inicial', models.DateField(default=None, max_length=10, verbose_name='Data Inicial')),
                ('prazo_contrato', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prazo')),
                ('data_final', models.DateField(max_length=10, verbose_name='Data Final')),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cadastros.imoveis')),
            ],
            options={
                'verbose_name': 'Contrato de Administração',
                'verbose_name_plural': 'Contrato de Administração',
            },
        ),
    ]
