# Generated by Django 4.1.5 on 2023-01-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_cep_imovel_imoveis_cep_and_more'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('proprietario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cadastros.clientes', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Contrato de Administração',
                'verbose_name_plural': 'Contrato de Administração',
            },
        ),
        migrations.DeleteModel(
            name='Contrato_Administracao',
        ),
    ]
