# Generated by Django 4.1.6 on 2023-02-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_rename_periodo_meses_aluguel_prazo_do_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluguel',
            old_name='prazo_do_contrato',
            new_name='prazo_contrato',
        ),
    ]
