# Generated by Django 4.1.5 on 2023-01-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_cep_imovel_imoveis_cep_and_more'),
        ('contratos', '0002_administracao_delete_contrato_administracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='nome',
        ),
        migrations.AddField(
            model_name='administracao',
            name='imovel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Imoveis.proprietario +', to='cadastros.imoveis', verbose_name='Imóvel'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='proprietario',
            field=models.ForeignKey(default=None, limit_choices_to={'qualificacao': 'PROPRIETARIO'}, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes.proprietario +', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
    ]
