# Generated by Django 4.1.5 on 2023-01-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_remove_administracao_nome_administracao_imovel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='imovel',
        ),
    ]
