# Generated by Django 4.1.5 on 2023-01-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_administracao_imovel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='imovel',
        ),
    ]
