# Generated by Django 4.1.6 on 2023-02-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_clientepj_nome_fantasia'),
        ('contratos', '0006_alter_aluguel_fiador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='fiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes_Fiador +', to='cadastros.clientes', verbose_name='Fiador'),
        ),
    ]
