# Generated by Django 4.1.6 on 2023-02-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_alter_aluguel_fiador'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='valor_caucao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor da caução'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='garantia',
            field=models.CharField(choices=[('Não possui', 'Não possui'), ('Caução', 'Caução'), ('Fiador', 'Fiador'), ('Seguro fiança', 'Seguro fiança'), ('Título de capitalização', 'Título de capitalização')], default='Não possui', max_length=50, verbose_name='Garantia'),
        ),
    ]
