# Generated by Django 4.1.5 on 2023-01-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_administracao_imovel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='imovel',
        ),
    ]
