# Generated by Django 4.1.5 on 2023-01-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_remove_administracao_imovel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='administracao',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
