# Generated by Django 4.1.5 on 2023-01-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alter_imoveis_endereco'),
        ('contratos', '0009_remove_administracao_proprietario_administracao_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='nome',
        ),
        migrations.AddField(
            model_name='administracao',
            name='proprietario',
            field=models.ForeignKey(default=None, limit_choices_to={'qualificacao': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes.proprietario +', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
    ]
