# Generated by Django 4.1.6 on 2023-02-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_aluguel_apolice_capitalizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='valor_caucao',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='valor_garantia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor'),
        ),
    ]
