# Generated by Django 4.1.6 on 2023-02-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_remove_aluguel_valor_caucao_aluguel_valor_garantia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='apolice_capitalizacao',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='banco_capitalizacao',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='apolice_garantia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='banco_garantia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco'),
        ),
    ]
