# Generated by Django 4.1.5 on 2023-01-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alter_imoveis_endereco'),
        ('contratos', '0013_alter_administracao_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='imovel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cadastros.imoveis', verbose_name='Imóvel'),
        ),
    ]
