# Generated by Django 4.1.6 on 2023-02-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_aluguel_seguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='taxa_admin_anual',
            field=models.CharField(blank=True, default=50, max_length=20, null=True, verbose_name='Tx Adm Anual'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='taxa_admin_mensal',
            field=models.CharField(blank=True, default=10, max_length=20, null=True, verbose_name='Tx Adm Mensal'),
        ),
    ]
