# Generated by Django 4.1.6 on 2023-02-26 13:14

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_imoveis_taxa_admin_anual_imoveis_taxa_admin_mensal'),
        ('contratos', '0014_aluguel_taxa_admin_anual_aluguel_taxa_admin_mensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='fiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.clientes', verbose_name='Fiador'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='imovel',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='proprietario', chained_model_field='proprietario', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.imoveis'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='taxa_admin_mensal',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='taxa_admin_mensal', chained_model_field='contratos.Aluguel.taxa_admin_mensal', default=None, on_delete=django.db.models.deletion.PROTECT, to='cadastros.imoveis'),
        ),
    ]
