# Generated by Django 4.1.6 on 2023-02-26 13:31

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_remove_saida_de_chaves_taxa_admin_anual_and_more'),
        ('contratos', '0015_alter_aluguel_fiador_alter_aluguel_imovel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='taxa_admin_anual',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='taxa_admin_anual', chained_model_field='taxa_admin_anual', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.imoveis', verbose_name='Taxa anual (%)'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='taxa_admin_mensal',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='taxa_admin_mensal', chained_model_field='taxa_admin_mensal', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.imoveis', verbose_name='Taxa mensal (%)'),
        ),
    ]
