# Generated by Django 4.1.6 on 2023-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_alter_aluguel_taxa_admin_anual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='taxa_admin_anual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tx Adm Mensal (%)'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='taxa_admin_mensal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tx Adm Mensal (%)'),
        ),
    ]
