# Generated by Django 4.1.5 on 2023-01-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_alter_administracao_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='dia_do_repasse',
            field=models.CharField(choices=[('DIA FIXO', 'Dia fixo'), ('DIAS UTEIS', 'Dias úteis após o vencimento do aluguel'), ('DIAS CORRIDOS', 'Dias corridos após o vencimento do aluguel')], default=None, max_length=100, verbose_name='Dia do repasse'),
        ),
        migrations.AddField(
            model_name='administracao',
            name='repasse_garantido',
            field=models.CharField(blank=True, choices=[('NAO POSSUI', 'Não possui'), ('TODO CONTRATO', 'Garantir por todo contrato')], default=None, max_length=100, null=True, verbose_name='Repasse Garantido'),
        ),
    ]
