# Generated by Django 4.1.6 on 2023-02-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_alter_aluguel_taxa_admin_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='comissao',
            field=models.FloatField(blank=True, null=True, verbose_name='Comissão'),
        ),
    ]
