# Generated by Django 4.1.5 on 2023-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0019_remove_administracao_dia_do_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='dia_do_repasse',
            field=models.CharField(blank=True, choices=[('DIA FIXO', 'Dia fixo'), ('DIAS UTEIS', 'Dias úteis após o vencimento do aluguel'), ('DIAS CORRIDOS', 'Dias corridos após o vencimento do aluguel')], default=None, max_length=100, null=True, verbose_name='Dia do repasse'),
        ),
    ]
