# Generated by Django 4.1.6 on 2023-02-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_financeiro_do_contrato_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='repasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Comissão'),
        ),
    ]
