# Generated by Django 4.1.5 on 2023-01-30 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_administracao_dia_do_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='valor_aluguel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do aluguel'),
        ),
    ]
