# Generated by Django 4.1.6 on 2023-02-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_financeiro_do_contrato_valor_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor pago'),
        ),
    ]
