# Generated by Django 4.1.5 on 2023-01-30 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_administracao_valor_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='prazo_locacao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prazo de Aluguel'),
        ),
        migrations.AddField(
            model_name='administracao',
            name='taxa_admin_anual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tx Adm Anual'),
        ),
        migrations.AddField(
            model_name='administracao',
            name='taxa_admin_mensal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tx Adm Mensal'),
        ),
    ]
