# Generated by Django 4.1.5 on 2023-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_administracao_prazo_locacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='data_final',
            field=models.DateField(blank=True, default=None, max_length=10, null=True, verbose_name='Data Final'),
        ),
        migrations.AddField(
            model_name='administracao',
            name='data_inicial',
            field=models.DateField(blank=True, default=None, max_length=10, null=True, verbose_name='Data Inicial'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='dia_do_repasse',
            field=models.CharField(choices=[('DIAS UTEIS', 'Dias úteis após o vencimento do aluguel'), ('DIAS CORRIDOS', 'Dias corridos após o vencimento do aluguel')], default=None, max_length=100, verbose_name='Dia do repasse'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='repasse_garantido',
            field=models.CharField(choices=[('NAO POSSUI', 'Não possui'), ('TODO CONTRATO', 'Garantir por todo contrato')], default=None, max_length=100, verbose_name='Repasse Garantido'),
        ),
    ]
