# Generated by Django 4.1.6 on 2023-02-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_financeiro_do_contrato_saldo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro_do_contrato',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data pagamento'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='vencimento_real',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Vencimento real'),
        ),
    ]
