# Generated by Django 4.1.6 on 2023-02-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_remove_financeiro_do_contrato_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='locatario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Locatario'),
        ),
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='proprietario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Proprietario'),
        ),
    ]
