# Generated by Django 4.1.5 on 2023-01-30 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_administracao_data_final_administracao_data_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracao',
            name='data_final',
            field=models.DateField(default=None, max_length=10, verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='data_inicial',
            field=models.DateField(default=None, max_length=10, verbose_name='Data Inicial'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='prazo_locacao',
            field=models.IntegerField(default=36, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prazo de Aluguel'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='taxa_admin_anual',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tx Adm Anual'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='taxa_admin_mensal',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tx Adm Mensal'),
        ),
    ]
