# Generated by Django 4.1.6 on 2023-02-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0024_financeiro_do_contrato_locatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='vencimento_repasse',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Vencimento repasse'),
        ),
    ]
