# Generated by Django 4.1.6 on 2023-02-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0025_financeiro_do_contrato_vencimento_repasse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='dias_para_repasse',
        ),
        migrations.RemoveField(
            model_name='administracao',
            name='regra_do_repasse',
        ),
        migrations.RemoveField(
            model_name='administracao',
            name='repasse_garantido',
        ),
    ]
