# Generated by Django 4.1.5 on 2023-02-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0025_alter_administracao_proprietario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administracao',
            old_name='prazo_locacao',
            new_name='prazo_contrato',
        ),
        migrations.AlterField(
            model_name='administracao',
            name='data_final',
            field=models.DateField(max_length=10, verbose_name='Data Final'),
        ),
    ]
