# Generated by Django 4.1.6 on 2023-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0026_remove_administracao_dias_para_repasse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='data_repasse',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Data repasse'),
        ),
    ]
