# Generated by Django 4.1.5 on 2023-02-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_alter_clientes_complemento_alter_clientes_cpf_and_more'),
        ('contratos', '0026_rename_prazo_locacao_administracao_prazo_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='dias_para_repasse',
            field=models.IntegerField(choices=[('DIAS UTEIS', 'Dias úteis após o vencimento do aluguel'), ('DIAS CORRIDOS', 'Dias corridos após o vencimento do aluguel')], default=None, max_length=100, verbose_name='Dia para repasse'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='proprietario',
            field=models.ForeignKey(default=None, limit_choices_to={'qualificacao': 'Proprietário'}, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes_proprietario +', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='repasse_garantido',
            field=models.CharField(choices=[('Não possui', 'Não possui'), ('Todo contrato', 'Garantir por todo contrato')], default=None, max_length=100, verbose_name='Repasse Garantido'),
        ),
    ]
