# Generated by Django 4.1.6 on 2023-02-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0027_financeiro_do_contrato_data_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='valor_repassado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor repassado'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='data_repasse',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Data do repasse'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='repasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor do Repasse'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor do Aluguel'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='vencimento_repasse',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Vcto do repasse'),
        ),
    ]
