# Generated by Django 4.1.6 on 2023-02-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0029_financeiro_do_contrato_saldo_repasse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeiro_do_contrato',
            old_name='valor',
            new_name='valor_aluguel',
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='saldo_repasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Saldo a repassar'),
        ),
    ]
