# Generated by Django 4.1.6 on 2023-02-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0030_rename_valor_financeiro_do_contrato_valor_aluguel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeiro_do_contrato',
            old_name='saldo',
            new_name='saldo_aluguel',
        ),
    ]
