# Generated by Django 4.1.6 on 2023-02-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0031_rename_saldo_financeiro_do_contrato_saldo_aluguel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeiro_do_contrato',
            old_name='repasse',
            new_name='valor_repasse',
        ),
    ]
