# Generated by Django 4.1.5 on 2023-02-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0032_alter_administracao_dias_para_repasse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='dia_do_repasse',
        ),
        migrations.AddField(
            model_name='administracao',
            name='regra_do_repasse',
            field=models.CharField(choices=[('DIAS UTEIS', 'Dias úteis após o vencimento do aluguel'), ('DIAS CORRIDOS', 'Dias corridos após o vencimento do aluguel')], default=None, max_length=100, verbose_name='Dia do repasse'),
        ),
    ]
