# Generated by Django 4.1.6 on 2023-02-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0032_rename_repasse_financeiro_do_contrato_valor_repasse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro_do_contrato',
            name='locatario',
        ),
        migrations.RemoveField(
            model_name='financeiro_do_contrato',
            name='proprietario',
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='taxa_admin_anual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tx adm anual (%)'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='taxa_admin_mensal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tx adm mensal (%)'),
        ),
    ]
