# Generated by Django 4.1.6 on 2023-03-02 10:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_alter_imoveis_complemento'),
        ('contratos', '0033_remove_financeiro_do_contrato_locatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='taxa_admin_anual',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='proprietario', chained_model_field='proprietario', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.imoveis'),
        ),
    ]
