# Generated by Django 4.1.5 on 2023-02-10 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_alter_clientes_celular_and_more'),
        ('contratos', '0034_alter_administracao_dias_para_repasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracao',
            name='dias_para_repasse',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Dias para repasse'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='prazo_contrato',
            field=models.IntegerField(default=36, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='regra_do_repasse',
            field=models.CharField(choices=[('DIAS UTEIS', 'Dias úteis após o vencimento do aluguel'), ('DIAS CORRIDOS', 'Dias corridos após o vencimento do aluguel')], default=None, max_length=100, verbose_name='Regra do repasse'),
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fianca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo fiança')),
                ('finalidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Finalidade')),
                ('data_inicial', models.DateField(blank=True, null=True, verbose_name='Data inicial')),
                ('periodo_meses', models.IntegerField(blank=True, null=True, verbose_name='Período')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('valor_contrato', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.imoveis', verbose_name='Imóvel')),
                ('locatario', models.ForeignKey(blank=True, limit_choices_to='Locatario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locatario', to='cadastros.clientes', verbose_name='Locatário')),
            ],
            options={
                'verbose_name': 'Contrato de Aluguel',
                'verbose_name_plural': 'Contrato de Aluguel',
            },
        ),
    ]
