# Generated by Django 4.1.6 on 2023-03-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0036_remove_aluguel_taxa_admin_anual'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='taxa_admin_anual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tx adm anual (%)'),
        ),
    ]
