# Generated by Django 4.1.6 on 2023-03-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_alter_imoveis_complemento'),
        ('contratos', '0037_aluguel_taxa_admin_anual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='proprietario',
        ),
        migrations.AlterField(
            model_name='administracao',
            name='imovel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cadastros.imoveis'),
        ),
    ]
