# Generated by Django 4.1.5 on 2023-02-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_alter_clientes_celular_and_more'),
        ('contratos', '0037_alter_aluguel_locatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='proprietario',
            field=models.ForeignKey(default=None, limit_choices_to={'qualificacao': 'Proprietário'}, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes_proprietario +', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='finalidade',
            field=models.CharField(blank=True, choices=[('Comercial', 'Comercial'), ('Industrial', 'Industrial'), ('Residencial', 'Residencial'), ('Temporada', 'Temporada')], max_length=50, null=True, verbose_name='Finalidade'),
        ),
    ]
