# Generated by Django 4.1.5 on 2023-02-10 19:07

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_alter_clientes_celular_and_more'),
        ('contratos', '0038_aluguel_proprietario_alter_aluguel_finalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='tipo_fianca',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='garantia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Garantia'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='imovel',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='proprietario', chained_model_field='proprietario', default=None, on_delete=django.db.models.deletion.PROTECT, to='cadastros.imoveis'),
        ),
    ]
