# Generated by Django 4.1.6 on 2023-03-02 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0038_remove_administracao_proprietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='proprietario',
            field=models.CharField(default=None, max_length=20, verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='prazo_contrato',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prazo'),
        ),
    ]
