# Generated by Django 4.1.6 on 2023-03-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0039_administracao_proprietario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='proprietario',
        ),
    ]
