# Generated by Django 4.1.6 on 2023-02-13 18:30

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_alter_clientes_celular_and_more'),
        ('contratos', '0039_remove_aluguel_tipo_fianca_aluguel_garantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='dias_para_repasse',
            field=models.ForeignKey(blank=True, limit_choices_to={'imovel': smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='proprietario', chained_model_field='proprietario', default=None, on_delete=django.db.models.deletion.PROTECT, to='cadastros.imoveis')}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratos.administracao'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='taxa_admin_anual',
            field=models.CharField(default=50, max_length=20, verbose_name='Tx Adm Anual'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='taxa_admin_mensal',
            field=models.CharField(default=10, max_length=20, verbose_name='Tx Adm Mensal'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='valor_aluguel',
            field=models.CharField(default=None, max_length=20, verbose_name='Valor do aluguel'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='garantia',
            field=models.CharField(blank=True, choices=[('Caução', 'Caução'), ('Fiador', 'Fiador'), ('Seguro fiança', 'Seguro fiança'), ('Título de capitalização', 'Título de capitalização'), ('Não possui', 'Não possui')], max_length=50, null=True, verbose_name='Garantia'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='locatario',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'qualificacao': 'Locatário'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locatario +', to='cadastros.clientes', verbose_name='Locatário'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='periodo_meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Período (em meses)'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='valor_contrato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor do aluguel'),
        ),
    ]
