# Generated by Django 4.1.6 on 2023-02-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0040_aluguel_dias_para_repasse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='regra_do_repasse',
            field=models.CharField(choices=[('DIAS UTEIS', 'Dias úteis após o vencimento do aluguel'), ('DIAS CORRIDOS', 'Dias corridos após o vencimento do aluguel')], default=None, max_length=100, verbose_name='Regra do repasse'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='repasse_garantido',
            field=models.CharField(choices=[('Não possui', 'Não possui'), ('Todo contrato', 'Garantir por todo contrato')], default=None, max_length=100, verbose_name='Repasse Garantido'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='dias_para_repasse',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Dias para repasse'),
        ),
    ]
