# Generated by Django 4.1.6 on 2023-02-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0041_aluguel_regra_do_repasse_aluguel_repasse_garantido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='regra_do_repasse',
            field=models.CharField(blank=True, choices=[('DIAS UTEIS', 'Dias úteis após o vencimento do aluguel'), ('DIAS CORRIDOS', 'Dias corridos após o vencimento do aluguel')], default=None, max_length=100, null=True, verbose_name='Regra do repasse'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='repasse_garantido',
            field=models.CharField(blank=True, choices=[('Não possui', 'Não possui'), ('Todo contrato', 'Garantir por todo contrato')], default=None, max_length=100, null=True, verbose_name='Repasse Garantido'),
        ),
    ]
