# Generated by Django 4.1.6 on 2023-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0042_alter_aluguel_regra_do_repasse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro_do_Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contrato')),
                ('vencimento', models.DateField(blank=True, max_length=10, null=True, verbose_name='Vencimento')),
                ('parcela', models.CharField(blank=True, max_length=10, null=True, verbose_name='Parcela')),
                ('valor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Valor')),
                ('multa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Multa')),
                ('juros', models.CharField(blank=True, max_length=10, null=True, verbose_name='Juros')),
                ('valor_total', models.CharField(blank=True, max_length=10, null=True, verbose_name='Valor Total')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Alugueis',
            },
        ),
    ]
