# Generated by Django 4.1.6 on 2023-02-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0043_financeiro_do_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro_do_contrato',
            options={'verbose_name': 'Financeiro', 'verbose_name_plural': 'Financeiro do Contrato'},
        ),
    ]
