# Generated by Django 4.1.6 on 2023-02-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0044_alter_financeiro_do_contrato_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.aluguel'),
        ),
    ]
