# Generated by Django 4.1.6 on 2023-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0045_alter_financeiro_do_contrato_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Pagamento'),
        ),
    ]
