# Generated by Django 4.1.6 on 2023-02-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0046_financeiro_do_contrato_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro_do_contrato',
            name='vencimento_real',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vencimento Real'),
        ),
    ]
