# Generated by Django 4.1.6 on 2023-02-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0047_financeiro_do_contrato_vencimento_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato +', to='contratos.aluguel', verbose_name='Locatário e Imóvel'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='vencimento',
            field=models.DateField(max_length=10, verbose_name='Vencimento'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='vencimento_real',
            field=models.DateField(max_length=20, verbose_name='Vencimento Real'),
        ),
    ]
