# Generated by Django 4.1.6 on 2023-02-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0048_alter_financeiro_do_contrato_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor'),
        ),
    ]
