# Generated by Django 4.1.6 on 2023-02-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0049_alter_financeiro_do_contrato_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor total'),
        ),
    ]
