# Generated by Django 4.1.6 on 2023-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0050_alter_financeiro_do_contrato_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='juros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Juros'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='multa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Multa'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='parcela',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='vencimento_real',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Vencimento Real'),
        ),
    ]
