# Generated by Django 4.1.6 on 2023-02-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_alter_imoveis_proprietario'),
        ('contratos', '0051_alter_financeiro_do_contrato_juros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='locatario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locatario +', to='cadastros.clientes', verbose_name='Locatário'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='proprietario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes_proprietario +', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='financeiro_do_contrato',
            name='parcela',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True, verbose_name='Parcela'),
        ),
    ]
