# Generated by Django 4.1.6 on 2023-02-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_alter_imoveis_proprietario'),
        ('contratos', '0052_alter_aluguel_locatario_alter_aluguel_proprietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracao',
            name='proprietario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes_proprietario +', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
    ]
