# Generated by Django 4.1.6 on 2023-02-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0043_clientesssss_pj_proprietario'),
        ('contratos', '0054_alter_financeiro_do_contrato_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracao',
            name='proprietario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes_proprietario +', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='locatario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locatario +', to='cadastros.clientes', verbose_name='Locatário'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='proprietario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Clientes_proprietario +', to='cadastros.clientes', verbose_name='Proprietário'),
        ),
    ]
